### ISSUE TITLE
[docs request] Blueprint example tutorials

### ISSUE THREAD

**Issue by larsbutler** [checkmate/chessboard#19]
It would be really helpful for chessboard/checkmate users/developers to have a set of practical hands-on blueprint writing tutorials. To start with, it would be useful to have at least one of each of the following:

- a simple blueprint
- a moderately complex blueprint
- a complex blueprint

In contrast to README-style documentation, these should be step-by-step walkthroughs. Example of such documentation are the [docker tutorials](https://docs.docker.com/) and [ZeroVM application tutorials ](http://zerovm.readthedocs.org/index.html#zerocloud-cloud-storage-compute-platform) *.

* I personally wrote the ZeroVM tutorials, and drew from the docker tutorials as a guide for style. In other words, I intended them the to practical, hands on, and specific.

**Comment by ziadsawalha** [comment]
Sample text for comments:

# Blueprint Authoring Tutorial

## Just one, CentOS 6 server

One of the simplest blueprints to write is a blueprint that has just one
service which spins up a CentOS 6 server with ssh enabled.

We would start with the required parts `topology`, `services`, a service that
we name, a `component` in the service, and information about the component that
would be sufficient to provide us the capabilities we seek:

```yaml

topology:
  services:
    "any name":
      component:
        <attributes of the component>
```

If we want the correct type of server returned (as opposed to a Windows server or any flavor of linux), we specify the following under `component`:
- Since we're looking for a server, we add `resource_type: compute`.
- Since we want to access it over ssh, we add `interface: ssh`.
- Since we want it to be a CentOS 6 server, we add an `os: CentOS 6` constraint.

```yaml

topology:
  name: Just a single CentOS 6 Server
  description: |
    This is a simple topology with a single CentOS 6 server
    that has ssh enabled.
  services:
    my-ssh-server:
      component:
        resource_type: compute
        interface: ssh
        constraints:
        - os: CentOS 6
```

This can now be launched using `pawn deploy <the file name>`

## Load-balancing a custom web server

```yaml

topology:
  name: A load-balanced web server
  description: |
    This is a simple topology for a load-balanced web service.
  services:
    lb:
      component:
        resource_type: load-balancer
        interface: http
      relations:
      - web: http
    web:
      component:
        provides:
        - application: http
        requires:
        - python: '>=2.4.0'
          # or: python: />=2.4.0
          # or: resource_type: application
          #     interface: python
          #     constraints:
          #     - setting: version
          #       greater-than-or-equal: 2.4.0
        scripts:
          start: |
            sudo python -m SimpleHTTPServer 80
        # If you were using ruby:
        # requires:
        # - application: ruby
        # scripts:
        #   install: |
        #     sudo gem install sinatra   # install dependency
        #   start: |
        #     sudo ruby -rsinatra -e'set :public_folder, "."; set :port, 80'
      count: 2
```

**Comment by larsbutler** [comment]
@ziadsawalha What I was hoping for were examples of blueprints using the _existing_ checkmatefile syntax, not the future/proposed checkmatefile syntax. This is for the benefit of the [schema validator and parser code](https://github.com/checkmate/chessboard/pull/20) that I just put up; if we can get the current schema defined, with thorough validation rules, we can soon start using Chessboard directly in Checkmate, which help us catch issues like [this](https://github.com/AutomationSupport/magentostack/pull/186) much sooner and in an automated fashion.

**Comment by ziadsawalha** [comment]
Updated:

# Blueprint Authoring Tutorial

## Just one, CentOS 6 server

One of the simplest blueprints to write is a blueprint that has just one
service which spins up a CentOS 6 server with ssh enabled.

We would start with the required parts `blueprint`, `services`, a service that
we name, a `component` in the service, and information about the component that
would be sufficient to provide us the capabilities we seek:

```yaml

blueprint:
  services:
    "any name":
      component:
        <attributes of the component>
```

Since we're looking for a server, we add `resource_type: compute`.
Since we want to access it over ssh, we add `interface: ssh`.
Since we want it to be a CentOS 6 server, we add an `os: CentOS 6` constraint.

```yaml

blueprint:
  name: Just a single CentOS 6.6 Server
  description: |
    This is a simple blueprint with a single CentOS 6 server
    that has ssh enabled.
  services:
    my-ssh-server:
      component:
        resource_type: compute
        interface: ssh
        constraints:
        - os: CentOS 6.6
```

We will soon be adding provider support from the command-line, but for now add

```yaml
environment:
  providers:
    nova:
      vendor: rackspace
      constraints:
      - region: IAD
```
to launch this using `pawn deploy <the file name>`


# Load-balancing a custom web server

```yaml

blueprint:
  name: A load-balanced web server
  description: |
    This is a simple blueprint for a load-balanced web service.
  services:
    lb:
      component:
        resource_type: load-balancer
        interface: http
      relations:
      - web: http
    web:
      component:
        id: sample_component
      constraints:
      - setting: os
        value: Ubuntu 15.04
        provider: nova
environment:
  providers:
    nova:
      vendor: rackspace
      constraints:
      - region: IAD
    load-balancer:
      vendor: rackspace
      constraints:
      - region: IAD
    script:
      vendor: core
      catalog:
        application:
          sample_component:
            provides:
            - application: http
            requires:
            - host: linux
            properties:
              scripts:
                install:
                  template: |
                    apt-get update
                    apt-get install upstart -y
                    echo "start on runlevel [2345]" > /etc/init/sample.conf
                    echo "stop on runlevel [016]" >> /etc/init/sample.conf
                    echo "respawn" >> /etc/init/sample.conf
                    echo "exec python -m SimpleHTTPServer 80" >> /etc/init/sample.conf
                    start sample
```






## DESIRED/FUTURE STATE: Load-balancing a custom web server

```yaml

blueprint:
  name: A load-balanced web server
  description: |
    This is a simple blueprint for a load-balanced web service.
  services:
    lb:
      component:
        resource_type: load-balancer
        interface: http
      relations:
      - web: http
    web:
      component:
        provides:
        - application: http
        requires:
        - python: '>=2.4.0'
          # or: python: />=2.4.0
          # or: resource_type: application
          #     interface: python
          #     constraints:
          #     - setting: version
          #       greater-than-or-equal: 2.4.0
        scripts:
          start: |
            sudo python -m SimpleHTTPServer 80
        # If you were using ruby:
        # requires:
        # - application: ruby
        # scripts:
        #   install: |
        #     sudo gem install sinatra   # install dependency
        #   start: |
        #     sudo ruby -rsinatra -e'set :public_folder, "."; set :port, 80'
      count: 2
```
