### ISSUE TITLE
Checkmatefile parser and schema definition/validator

### ISSUE THREAD

**Issue by larsbutler** [checkmate/chessboard#7]
We need to implement `Checkmatefile` parser code. Here's what the general workflow looks like:

1. Read `Checkmatefile` (yaml/json load)
2. Validate schema (check syntax of `Checkmatefile`)
3.

Tasks:

- [x] Define `Checkmatefile` schema (using [voluptuous](https://pypi.python.org/pypi/voluptuous), perhaps)
  - [x] Initial draft (done: https://github.com/checkmate/chessboard/pull/20)
  - [ ] Complete, comprehensive schema (blocked; need comprehensive docs/spec of schema)
- [x] Write a `Checkmatefile` parser which loads yaml from a file into a dict-like structure, and then runs the schema validation. If validation fails, raise an exception with some context (for example, where in the document hierarchy the error was found). If it succeeds, just return the contents of the `Checkmatefile` as a Python `dict` object.

**Comment by ziadsawalha** [comment]
Some additional requirements:
- [ ] Maintain part (or all) of the schema in a YAML file that includes markdown documentation so it can be used to parse the schema in any language (jvascript, for example) and generate useful error messages that come from the YAML file. I.e. the docs and error messages should be DRY (not repeated in multiple places)
Example:
```yaml
schema:
  id:
    type: string
    description: a value to identify a deployment by
    constraints:
    - regex: ....
      message: |
        'id' is an alphanumeric string from 4 to
        32 characters in length. It cannot start 
        with a number, …
    documentation: |
      very long markdown....
```

```python
def test_schema(self):
    invalid_deployment = """
        id: 1
    """
    with self.assertRaisesRegexp(CheckmateValidationError,
                                 "'id' must be a string") as exc:
        parser.parse(invalid_document)
        self.assertEquals(exc.docs, "'id' is an alphanumeric string from 4 to "
                                    "32 characters in length. It cannot start "
                                    "with a number, …")
       self.assertEquals(exc.location, {'line': 2, 'position': 7, 'line': "id': 1"}
```
- [ ] Keep parse logic separate from any provider/planning logic so that we can parse easily without API interactions or loading many libraries.
- [ ] Make parsers easily loadable as libraries (i.e. in pawn, checkmate, etc...)
- [ ] Maintain line numbers and character positions for any errors so metadata can be returned to a client that can be used to display or highlight where an error happened.
