### ISSUE TITLE
Add ad-hoc component definitions to `Checkmatefile`

### ISSUE THREAD

**Issue by larsbutler** [checkmate/chessboard#9]
We need to be able to define custom components in a `Checkmatefile`. After some "whiteboarding" in an etherpad with @ziadsawalha, we think the structure should look  something like the following. It still needs work.

```
blueprint:
  ...  # `blueprint` is already part of Checkmatefiles, and is just shown here for context.
components:
  <name-of-component>:
    commands:
      # these are all lists of shell commands, basically
      start: ["service foo start --port {{ port }}"]
      install: [
        "apt-get update",
        "apt-get install foo",
      ]
      stop: ["service foo stop"]
      kill: ["pkill foo", "rm /tmp/something/to/clean/up"]
      test: ["curl localhost:{{ port }}"]
    options:
      port:
        get_from:
          # env, etcd, and keychain are well-known keywords here
          # try to get the value from these places, in this particular order
          - env: FOO_PORT
          - etcd: /var/foo_port
          - keychain: foo_port
        # if env/etcd/keychain don't have the value we want, use the default:
        default: {{ get_random_free_port() }}
      provides:
        - http
      requires:
        - host: linux
```

Each provider will inherently include a basic set of "primitive" components. For example, a Rackspace provider will include components like load balancers, compute nodes, object storage, and cloud databases (Redis, MongoDB, etc.).

The idea is that custom components can be defined in a Checkmatefile, which are then added to a provider's catalog at runtime.
